// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	aboutUsSidebar: [{ type: 'autogenerated', dirName: 'about' }],
	projectsSidebar: [{ type: 'autogenerated', dirName: 'projects' }],
};

export default sidebars;
